# -*- coding: utf-8 -*-

import os
import logging
from datetime import datetime
from typing import Dict, List, Any, Optional

_logger = logging.getLogger(__name__)


class RobotGenerator:
    """Service for generating Robot Framework test files"""
    
    def __init__(self, config):
        """
        Initialize Robot Generator
        
        Args:
            config: qa.test.ai.config record
        """
        self.config = config
        self.output_path = config.output_path
        self.base_url = config.test_base_url
        self.username = config.test_username
        self.password = config.test_password
        self.browser = config.browser
        self.timeout = config.timeout
        self.headless = config.headless
    
    def generate_single_test_file(self, test_case) -> str:
        """
        Generate a single .robot file for a test case
        
        Args:
            test_case: qa.test.case record
        
        Returns:
            Robot Framework file content as string
        """
        content = self._get_file_header(test_case)
        content += self._get_variables_section()
        content += test_case.robot_code
        content += "\n\n"
        content += self._get_common_keywords()
        
        return content
    
    def export_suite(self, suite) -> List[str]:
        """
        Export all tests in a suite as Robot Framework files
        
        Args:
            suite: qa.test.suite record
        
        Returns:
            List of generated file paths
        """
        # Create output directory
        suite_dir = os.path.join(self.output_path, suite.name.replace(' ', '_'))
        os.makedirs(suite_dir, exist_ok=True)
        
        file_paths = []
        
        # Generate resource file
        resource_path = os.path.join(suite_dir, 'resources.robot')
        with open(resource_path, 'w') as f:
            f.write(self._generate_resource_file())
        file_paths.append(resource_path)
        
        # Generate test files
        for test_case in suite.test_case_ids:
            file_name = f"{test_case.test_id}_{test_case.name.replace(' ', '_')}.robot"
            file_path = os.path.join(suite_dir, file_name)
            
            content = self.generate_single_test_file(test_case)
            
            with open(file_path, 'w') as f:
                f.write(content)
            
            file_paths.append(file_path)
            _logger.info(f"Generated test file: {file_path}")
        
        # Generate __init__.robot for suite
        init_path = os.path.join(suite_dir, '__init__.robot')
        with open(init_path, 'w') as f:
            f.write(self._generate_init_file(suite))
        file_paths.append(init_path)
        
        return file_paths
    
    def export_all_tests(self, test_cases) -> str:
        """
        Export multiple test cases to a single .robot file
        
        Args:
            test_cases: List of qa.test.case records
        
        Returns:
            Path to generated file
        """
        os.makedirs(self.output_path, exist_ok=True)
        
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        file_path = os.path.join(self.output_path, f'tests_{timestamp}.robot')
        
        content = self._get_combined_header()
        content += self._get_variables_section()
        content += "\n*** Test Cases ***\n"
        
        for test_case in test_cases:
            # Extract just the test case section from robot_code
            content += self._extract_test_cases(test_case.robot_code)
            content += "\n"
        
        content += "\n*** Keywords ***\n"
        content += self._get_common_keywords()
        
        with open(file_path, 'w') as f:
            f.write(content)
        
        return file_path
    
    def _get_file_header(self, test_case) -> str:
        """Generate file header for a test case"""
        return f"""*** Settings ***
Documentation    {test_case.description or test_case.name}
...              Generated by QA Test Generator
...              Specification: {test_case.spec_id.name if test_case.spec_id else 'N/A'}
...              Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Library          SeleniumLibrary
Library          String
Library          Collections
Library          DateTime

Resource         resources.robot

Suite Setup      Open Browser And Login
Suite Teardown   Close All Browsers
Test Teardown    Run Keyword If Test Failed    Capture Page Screenshot

"""
    
    def _get_combined_header(self) -> str:
        """Generate combined file header"""
        return f"""*** Settings ***
Documentation    Combined Test Suite
...              Generated by QA Test Generator
...              Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Library          SeleniumLibrary
Library          String
Library          Collections
Library          DateTime

Suite Setup      Open Browser And Login
Suite Teardown   Close All Browsers
Test Teardown    Run Keyword If Test Failed    Capture Page Screenshot

"""
    
    def _get_variables_section(self) -> str:
        """Generate variables section"""
        headless_opt = "--headless" if self.headless else ""
        
        return f"""*** Variables ***
${{BASE_URL}}                {self.base_url}
${{USERNAME}}                {self.username}
${{PASSWORD}}                {self.password}
${{BROWSER}}                 {self.browser}
${{TIMEOUT}}                 {self.timeout}s
${{IMPLICIT_WAIT}}           10s
${{HEADLESS_OPTIONS}}        {headless_opt}

# Common Locators
${{LOGIN_USERNAME}}          //input[@id='login']
${{LOGIN_PASSWORD}}          //input[@id='password']
${{LOGIN_BUTTON}}            //button[@type='submit']
${{HOME_MENU}}               //button[contains(@class,'o_menu_toggle')]
${{CREATE_BUTTON}}           //button[contains(@class,'o_list_button_add')]
${{SAVE_BUTTON}}             //button[contains(@class,'o_form_button_save')]
${{EDIT_BUTTON}}             //button[contains(@class,'o_form_button_edit')]

"""
    
    def _get_common_keywords(self) -> str:
        """Generate common keywords section"""
        return """*** Keywords ***
Open Browser And Login
    [Documentation]    Open browser and login to Odoo
    ${chrome_options}=    Evaluate    sys.modules['selenium.webdriver'].ChromeOptions()    sys
    Run Keyword If    '${HEADLESS_OPTIONS}' != ''    Call Method    ${chrome_options}    add_argument    --headless
    Call Method    ${chrome_options}    add_argument    --no-sandbox
    Call Method    ${chrome_options}    add_argument    --disable-dev-shm-usage
    Call Method    ${chrome_options}    add_argument    --window-size=1920,1080
    Create Webdriver    Chrome    options=${chrome_options}
    Go To    ${BASE_URL}
    Maximize Browser Window
    Set Selenium Implicit Wait    ${IMPLICIT_WAIT}
    Set Selenium Timeout    ${TIMEOUT}
    Login To Odoo

Login To Odoo
    [Documentation]    Perform Odoo login
    Wait Until Element Is Visible    ${LOGIN_USERNAME}    timeout=${TIMEOUT}
    Input Text    ${LOGIN_USERNAME}    ${USERNAME}
    Input Text    ${LOGIN_PASSWORD}    ${PASSWORD}
    Click Button    ${LOGIN_BUTTON}
    Wait Until Element Is Visible    ${HOME_MENU}    timeout=${TIMEOUT}
    Sleep    1s

Navigate To App
    [Documentation]    Navigate to an Odoo app
    [Arguments]    ${app_name}
    Click Element    ${HOME_MENU}
    Sleep    0.5s
    ${app_locator}=    Set Variable    //a[contains(@class,'o_app')]//span[contains(text(),'${app_name}')]/ancestor::a
    Wait Until Element Is Visible    ${app_locator}    timeout=${TIMEOUT}
    Click Element    ${app_locator}
    Wait Until Page Loaded

Wait Until Page Loaded
    [Documentation]    Wait for Odoo page to fully load
    Sleep    0.5s
    ${loading_visible}=    Run Keyword And Return Status    
    ...    Wait Until Element Is Not Visible    //div[contains(@class,'o_loading')]    timeout=5s
    Sleep    0.5s

Click Create Button
    [Documentation]    Click the Create/New button
    Wait Until Element Is Visible    ${CREATE_BUTTON}    timeout=${TIMEOUT}
    Click Element    ${CREATE_BUTTON}
    Wait Until Page Loaded

Click Save Button
    [Documentation]    Click the Save button
    ${save_visible}=    Run Keyword And Return Status    
    ...    Wait Until Element Is Visible    ${SAVE_BUTTON}    timeout=3s
    Run Keyword If    ${save_visible}    Click Element    ${SAVE_BUTTON}
    Wait Until Page Loaded

Input Field Value
    [Documentation]    Input value into an Odoo field
    [Arguments]    ${field_name}    ${value}
    ${locator}=    Set Variable    //div[@name='${field_name}']//input | //input[@id='${field_name}']
    Wait Until Element Is Visible    ${locator}    timeout=${TIMEOUT}
    Clear Element Text    ${locator}
    Input Text    ${locator}    ${value}

Select Many2One Value
    [Documentation]    Select value in Many2one field
    [Arguments]    ${field_name}    ${value}
    ${locator}=    Set Variable    //div[@name='${field_name}']//input
    Wait Until Element Is Visible    ${locator}    timeout=${TIMEOUT}
    Click Element    ${locator}
    Input Text    ${locator}    ${value}
    Sleep    1s
    ${dropdown}=    Set Variable    //ul[contains(@class,'ui-autocomplete')]//li//a | //ul[contains(@class,'o-autocomplete')]//a
    Wait Until Element Is Visible    ${dropdown}    timeout=5s
    Click Element    ${dropdown}
    Sleep    0.5s

Click Button By Name
    [Documentation]    Click Odoo button by name attribute
    [Arguments]    ${button_name}
    ${locator}=    Set Variable    //button[@name='${button_name}']
    Wait Until Element Is Visible    ${locator}    timeout=${TIMEOUT}
    Click Element    ${locator}
    Wait Until Page Loaded

Verify Status Badge
    [Documentation]    Verify status badge contains expected text
    [Arguments]    ${expected_status}
    ${locator}=    Set Variable    //span[contains(@class,'badge') and contains(text(),'${expected_status}')] | //button[contains(@class,'o_arrow_button') and contains(.,'${expected_status}')]
    Wait Until Element Is Visible    ${locator}    timeout=${TIMEOUT}

Verify Element Contains Value
    [Documentation]    Verify field contains expected value
    [Arguments]    ${field_name}    ${expected_value}
    ${locator}=    Set Variable    //div[@name='${field_name}']//input | //*[@name='${field_name}']
    Wait Until Element Is Visible    ${locator}    timeout=${TIMEOUT}
    ${actual}=    Get Value    ${locator}
    Should Contain    ${actual}    ${expected_value}

Confirm Dialog
    [Documentation]    Confirm popup dialog
    ${dialog}=    Set Variable    //footer//button[contains(@class,'btn-primary')] | //button[contains(@class,'btn-primary') and contains(@data-dismiss,'modal')]
    ${visible}=    Run Keyword And Return Status    
    ...    Wait Until Element Is Visible    ${dialog}    timeout=3s
    Run Keyword If    ${visible}    Click Element    ${dialog}
    Sleep    0.5s

"""
    
    def _generate_resource_file(self) -> str:
        """Generate shared resource file for suite"""
        return f"""*** Settings ***
Documentation    Shared resources for test suite
Library          SeleniumLibrary
Library          String
Library          Collections
Library          DateTime

{self._get_variables_section()}

{self._get_common_keywords()}
"""
    
    def _generate_init_file(self, suite) -> str:
        """Generate __init__.robot file for test suite"""
        return f"""*** Settings ***
Documentation    {suite.name}
...              {suite.description or 'Test Suite'}
...              Generated by QA Test Generator

Resource         resources.robot

Suite Setup      Open Browser And Login
Suite Teardown   Close All Browsers

Force Tags       {suite.include_tags or 'automated'}
Default Tags     {suite.name.lower().replace(' ', '_')}
"""
    
    def _extract_test_cases(self, robot_code: str) -> str:
        """Extract test cases section from robot code"""
        lines = robot_code.split('\n')
        in_test_cases = False
        result = []
        
        for line in lines:
            if '*** Test Cases ***' in line:
                in_test_cases = True
                continue
            elif '***' in line and 'Test Cases' not in line:
                in_test_cases = False
                continue
            
            if in_test_cases:
                result.append(line)
        
        return '\n'.join(result) if result else robot_code
