"""
AI Migration Agent Controller

This module provides an AI agent that can autonomously handle complex data migrations
by analyzing data, making decisions, and executing multi-step migration workflows.

The agent follows a structured approach:
1. Analyze source data and target model
2. Plan migration steps (dependencies, transformations)
3. Execute with human-in-the-loop approval for critical decisions
4. Monitor and adapt to errors
"""

import json
import logging
from datetime import datetime

from odoo import models, fields, api, _
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class MigrationAgent(models.Model):
    _name = 'migration.agent'
    _description = 'AI Migration Agent'
    _inherit = ['mail.thread', 'mail.activity.mixin']
    _order = 'create_date desc'

    name = fields.Char(
        string='Agent Name',
        required=True,
        default=lambda self: f"Migration Agent {datetime.now().strftime('%Y%m%d-%H%M%S')}",
    )
    
    state = fields.Selection([
        ('idle', 'Idle'),
        ('analyzing', 'Analyzing'),
        ('planning', 'Planning'),
        ('awaiting_approval', 'Awaiting Approval'),
        ('executing', 'Executing'),
        ('paused', 'Paused'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    ], default='idle', string='State', tracking=True)
    
    # Agent Configuration
    ai_provider = fields.Selection([
        ('anthropic', 'Anthropic Claude'),
        ('openai', 'OpenAI GPT'),
    ], string='AI Provider', default='anthropic', required=True)
    
    ai_model = fields.Char(
        string='AI Model',
        default='claude-sonnet-4-20250514',
        help='Specific model to use (e.g., claude-sonnet-4-20250514, gpt-4-turbo)',
    )
    
    autonomy_level = fields.Selection([
        ('supervised', 'Supervised - Approve all decisions'),
        ('semi_auto', 'Semi-Automatic - Approve critical only'),
        ('autonomous', 'Autonomous - Run without approval'),
    ], default='semi_auto', string='Autonomy Level')
    
    # Source Configuration
    source_file_ids = fields.Many2many(
        'ir.attachment',
        string='Source Files',
        help='One or more files to migrate',
    )
    
    # Target Configuration
    target_model_ids = fields.Many2many(
        'ir.model',
        string='Target Models',
        help='Models to populate (agent will determine import order)',
    )
    
    # Migration Projects
    project_ids = fields.One2many(
        'migration.project',
        'agent_id',
        string='Migration Projects',
    )
    
    # Agent Memory / Context
    agent_context = fields.Text(
        string='Agent Context',
        help='Persistent context for the agent across sessions',
    )
    
    # Execution Plan
    execution_plan = fields.Text(
        string='Execution Plan',
        help='JSON plan generated by the agent',
    )
    
    # Pending Decisions
    pending_decision_ids = fields.One2many(
        'migration.agent.decision',
        'agent_id',
        string='Pending Decisions',
    )
    
    # Statistics
    total_records_planned = fields.Integer(string='Records Planned', readonly=True)
    total_records_imported = fields.Integer(string='Records Imported', readonly=True)
    total_errors = fields.Integer(string='Total Errors', readonly=True)
    
    # Logs
    agent_log = fields.Text(string='Agent Log', readonly=True)
    
    def _log(self, message, level='info'):
        """Add entry to agent log."""
        timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        log_entry = f"[{timestamp}] [{level.upper()}] {message}\n"
        self.agent_log = (self.agent_log or '') + log_entry
        
        if level == 'error':
            _logger.error(f"Agent {self.id}: {message}")
        else:
            _logger.info(f"Agent {self.id}: {message}")
    
    def action_start(self):
        """Start the migration agent."""
        self.ensure_one()
        
        if not self.source_file_ids:
            raise UserError(_('Please attach source files first.'))
        
        if not self.target_model_ids:
            raise UserError(_('Please select target models.'))
        
        self.state = 'analyzing'
        self._log('Agent started - beginning analysis phase')
        
        # Run analysis
        self._analyze_sources()
        
        return True
    
    def action_pause(self):
        """Pause the agent."""
        self.state = 'paused'
        self._log('Agent paused by user')
    
    def action_resume(self):
        """Resume the agent."""
        if self.state == 'paused':
            self.state = 'executing'
            self._log('Agent resumed')
            self._execute_next_step()
    
    def action_stop(self):
        """Stop and reset the agent."""
        self.state = 'idle'
        self._log('Agent stopped by user')
    
    def _analyze_sources(self):
        """Analyze source files and target models."""
        self._log('Analyzing source files...')
        
        analysis_results = []
        
        for attachment in self.source_file_ids:
            # Detect file type
            filename = attachment.name.lower()
            if filename.endswith('.csv'):
                file_type = 'csv'
            elif filename.endswith(('.xlsx', '.xls')):
                file_type = 'excel'
            elif filename.endswith('.json'):
                file_type = 'json'
            else:
                self._log(f'Unknown file type: {attachment.name}', 'warning')
                continue
            
            # Get file preview
            # ... (file parsing logic)
            
            analysis_results.append({
                'file_id': attachment.id,
                'filename': attachment.name,
                'file_type': file_type,
            })
        
        # Analyze target models
        target_info = []
        for model in self.target_model_ids:
            fields_info = self._get_model_fields_info(model)
            target_info.append({
                'model_id': model.id,
                'model_name': model.model,
                'model_label': model.name,
                'fields': fields_info,
            })
        
        # Use AI to create migration plan
        self.state = 'planning'
        self._log('Analysis complete - generating migration plan')
        
        plan = self._generate_migration_plan(analysis_results, target_info)
        self.execution_plan = json.dumps(plan, indent=2)
        
        # Check if approval needed
        if self.autonomy_level == 'supervised':
            self._create_plan_approval_decision(plan)
            self.state = 'awaiting_approval'
            self._log('Migration plan created - awaiting user approval')
        else:
            self.state = 'executing'
            self._log('Migration plan approved automatically - beginning execution')
            self._execute_next_step()
    
    def _get_model_fields_info(self, model):
        """Get relevant field information for a model."""
        fields = self.env['ir.model.fields'].search([
            ('model_id', '=', model.id),
            ('store', '=', True),
            ('name', 'not in', [
                'id', 'create_uid', 'create_date', 'write_uid', 'write_date',
                '__last_update', 'display_name',
            ]),
        ])
        
        return [{
            'name': f.name,
            'label': f.field_description,
            'type': f.ttype,
            'required': f.required,
            'relation': f.relation,
        } for f in fields]
    
    def _generate_migration_plan(self, source_analysis, target_info):
        """Use AI to generate a migration plan."""
        ai_service = self.env['migration.ai.service']
        
        prompt = f"""You are a data migration expert. Create a detailed migration plan.

SOURCE FILES:
{json.dumps(source_analysis, indent=2)}

TARGET MODELS:
{json.dumps(target_info, indent=2)}

Create a migration plan that:
1. Determines the optimal import order (considering foreign key dependencies)
2. Maps each source file to the appropriate target model
3. Identifies any potential data quality issues
4. Suggests transformations needed

RESPONSE FORMAT (JSON):
{{
    "import_order": ["model.name1", "model.name2", ...],
    "file_mappings": [
        {{
            "file_id": 123,
            "target_model": "model.name",
            "confidence": 0.95,
            "reasoning": "Why this mapping"
        }}
    ],
    "dependencies": [
        {{
            "model": "model.name",
            "depends_on": ["other.model"],
            "foreign_key_field": "field_name"
        }}
    ],
    "warnings": ["Any concerns"],
    "estimated_records": 1000,
    "estimated_duration_minutes": 5
}}

Respond with only valid JSON."""

        try:
            api_key = ai_service.get_api_key(self.ai_provider)
            
            if self.ai_provider == 'anthropic':
                response = ai_service._call_anthropic(api_key, prompt)
            else:
                response = ai_service._call_openai(api_key, prompt)
            
            # Parse response
            import re
            json_match = re.search(r'```(?:json)?\s*([\s\S]*?)\s*```', response)
            if json_match:
                json_str = json_match.group(1)
            else:
                json_str = response.strip()
            
            return json.loads(json_str)
            
        except Exception as e:
            self._log(f'AI planning failed: {e}', 'error')
            # Return a basic plan
            return {
                'import_order': [m.model for m in self.target_model_ids],
                'file_mappings': [],
                'dependencies': [],
                'warnings': [f'AI planning failed: {e}'],
            }
    
    def _create_plan_approval_decision(self, plan):
        """Create a decision record for plan approval."""
        self.env['migration.agent.decision'].create({
            'agent_id': self.id,
            'decision_type': 'plan_approval',
            'description': 'Approve the migration plan',
            'context_data': json.dumps(plan, indent=2),
            'options': json.dumps(['approve', 'reject', 'modify']),
        })
    
    def _execute_next_step(self):
        """Execute the next step in the migration plan."""
        if self.state not in ('executing',):
            return
        
        plan = json.loads(self.execution_plan) if self.execution_plan else {}
        import_order = plan.get('import_order', [])
        
        # Find next model to import
        for model_name in import_order:
            project = self.project_ids.filtered(
                lambda p: p.target_model_name == model_name and p.state != 'done'
            )
            
            if project and project.state == 'validated':
                self._log(f'Executing import for {model_name}')
                project.action_start_import()
                return
            elif not project:
                # Create project for this model
                self._create_project_for_model(model_name, plan)
                return
        
        # All done
        self.state = 'completed'
        self._log('All migrations completed successfully')
        self._update_statistics()
    
    def _create_project_for_model(self, model_name, plan):
        """Create a migration project for a specific model."""
        model = self.env['ir.model'].search([('model', '=', model_name)], limit=1)
        if not model:
            self._log(f'Model not found: {model_name}', 'error')
            return
        
        # Find matching file from plan
        file_mapping = next(
            (m for m in plan.get('file_mappings', []) if m.get('target_model') == model_name),
            None
        )
        
        if not file_mapping:
            self._log(f'No file mapping for model: {model_name}', 'warning')
            return
        
        attachment = self.env['ir.attachment'].browse(file_mapping['file_id'])
        
        # Create project
        project = self.env['migration.project'].create({
            'name': f"Agent Import: {model.name}",
            'source_type': 'csv',  # TODO: detect from file
            'source_file': attachment.datas,
            'source_filename': attachment.name,
            'target_model_id': model.id,
            'agent_id': self.id,
            'ai_provider': self.ai_provider,
        })
        
        # Parse and get AI mappings
        project._parse_source_file()
        
        # Run AI mapping
        ai_service = self.env['migration.ai.service']
        try:
            suggestions = ai_service.suggest_mappings(project)
            
            # Create mappings from suggestions
            for suggestion in suggestions.get('suggestions', []):
                if suggestion.get('confidence', 0) >= 0.7:
                    target_field = self.env['ir.model.fields'].search([
                        ('model_id', '=', project.target_model_id.id),
                        ('name', '=', suggestion.get('target_field')),
                    ], limit=1)
                    
                    if target_field:
                        self.env['migration.mapping'].create({
                            'project_id': project.id,
                            'source_column': suggestion['source_column'],
                            'target_field_id': target_field.id,
                            'ai_suggested': True,
                            'ai_confidence': suggestion.get('confidence', 0),
                        })
            
            # Validate
            project.action_validate()
            self._log(f'Project created and validated for {model_name}')
            
            # Continue execution
            self._execute_next_step()
            
        except Exception as e:
            self._log(f'Failed to setup project for {model_name}: {e}', 'error')
            
            if self.autonomy_level != 'autonomous':
                self._create_error_decision(project, str(e))
                self.state = 'awaiting_approval'
            else:
                self.state = 'failed'
    
    def _create_error_decision(self, project, error_message):
        """Create a decision for handling an error."""
        self.env['migration.agent.decision'].create({
            'agent_id': self.id,
            'decision_type': 'error_handling',
            'description': f'Error in project {project.name}: {error_message}',
            'context_data': json.dumps({
                'project_id': project.id,
                'error': error_message,
            }),
            'options': json.dumps(['retry', 'skip', 'abort']),
        })
    
    def _update_statistics(self):
        """Update agent statistics from projects."""
        self.total_records_imported = sum(self.project_ids.mapped('imported_count'))
        self.total_errors = sum(self.project_ids.mapped('error_count'))
        self.total_records_planned = sum(self.project_ids.mapped('total_rows'))


class MigrationAgentDecision(models.Model):
    _name = 'migration.agent.decision'
    _description = 'Agent Decision Point'
    _order = 'create_date desc'

    agent_id = fields.Many2one(
        'migration.agent',
        string='Agent',
        required=True,
        ondelete='cascade',
    )
    
    decision_type = fields.Selection([
        ('plan_approval', 'Plan Approval'),
        ('mapping_review', 'Mapping Review'),
        ('error_handling', 'Error Handling'),
        ('data_conflict', 'Data Conflict'),
        ('custom', 'Custom Decision'),
    ], string='Decision Type', required=True)
    
    description = fields.Text(string='Description')
    context_data = fields.Text(string='Context Data')
    options = fields.Text(string='Available Options')
    
    # Resolution
    state = fields.Selection([
        ('pending', 'Pending'),
        ('resolved', 'Resolved'),
        ('skipped', 'Skipped'),
    ], default='pending', string='State')
    
    resolution = fields.Char(string='Resolution')
    resolved_by = fields.Many2one('res.users', string='Resolved By')
    resolved_at = fields.Datetime(string='Resolved At')
    
    def action_resolve(self, resolution):
        """Resolve the decision."""
        self.ensure_one()
        self.write({
            'state': 'resolved',
            'resolution': resolution,
            'resolved_by': self.env.uid,
            'resolved_at': fields.Datetime.now(),
        })
        
        # Notify agent
        self.agent_id._log(f'Decision resolved: {self.decision_type} -> {resolution}')
        
        # Continue agent execution if it was waiting
        if self.agent_id.state == 'awaiting_approval':
            if resolution == 'approve' or resolution == 'retry':
                self.agent_id.state = 'executing'
                self.agent_id._execute_next_step()
            elif resolution == 'reject' or resolution == 'abort':
                self.agent_id.state = 'failed'
            elif resolution == 'skip':
                self.agent_id.state = 'executing'
                self.agent_id._execute_next_step()


# Add agent_id to migration project
class MigrationProjectAgent(models.Model):
    _inherit = 'migration.project'
    
    agent_id = fields.Many2one(
        'migration.agent',
        string='Migration Agent',
        ondelete='set null',
    )
